jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build
  test:
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Generate unit test coverage report
      run: ./gradlew jacocoTestReport
    - continue-on-error: true
      name: Run Android instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
    - continue-on-error: true
      name: Codecov
      uses: codecov/codecov-action@v3.1.0
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
